language: cpp
compiler: gcc
sudo: required
dist: trusty

before_script:
  - cd "$TRAVIS_BUILD_DIR/../"
  - git clone --depth=1 https://github.com/Tadly/KissFFT
  - mkdir -p ./KissFFT/build/ && cd ./KissFFT/build/
  - cmake ../ && sudo make install
  - cd "$TRAVIS_BUILD_DIR/../"
  - git clone --depth=1 -b add-spectrum-vis-processor https://github.com/AchimTuran/asplib
  - mkdir -p ./asplib/build/ && cd ./asplib/build/
  - cmake ../ && sudo make install

script:
  - cd "$TRAVIS_BUILD_DIR"
  - cmake ./ && make
